name: universal-ctags
summary: Parse source code to build an index of defined symbols.
adopt-info: universal-ctags
description: |
  ctags parses source code to produce an index file, mapping the names of
  symbols, like functions, classes, and variables, to the locations where
  they are defined. This index is used by editors like Vim and Emacs
  to enable feaures like 'go to definition'.
  
  Universal Ctags is a fork of the venerable Exuberant Ctags, that adds
  additional features, including support for more languages.
  
  # Usage
  
  When installed, this snap provides executable `universal-ctags`,
  and alias `ctags`.
  
  In order to read config from files under ~/.ctags.d/,
  you need to give the snap permission:
  
      sudo snap connect universal-ctags:dot-ctags
  
  See ctags online useage documentation at
  http://docs.ctags.io/en/latest/man-pages.html
  
  Limitations
  -----------
  
  Compared to universal-ctags installed using apt, this snap currently has some
  limitations:
  
  1. It can only access files that are both within the user's $HOME
     directory, and are not in hidden (with dot prefixed names.) This applies
     to both read source code, written tags files, and configuration files
     specified using the '--options' or '--options-maybe' args.
  2. The 'man' pages are not installed.
  3. The 'etags' executable alias (which defaults to Emacs style tags files)
     is not installed.

  If these or other issues cause you problems, let me know at
  https://github.com/universal-ctags/ctags-snap/issues

base: core18
grade: stable
confinement: strict

plugs:
  dot-ctags:
    interface: personal-files
    read: [$HOME/.ctags.d]

apps:
  universal-ctags:
    plugs: [home, dot-ctags]
    command: universal-ctags-wrapper

parts:
  universal-ctags:
    source-type: git
    source: https://github.com/universal-ctags/ctags.git
    plugin: autotools
    build-packages: [pkg-config]
    stage-packages: [libxml2]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "0.$(date -u +%Y-%m-%d+%H:%M:%S)+$(git show -s --format=%h)"
    override-prime: |
      snapcraftctl prime
      echo >universal-ctags-wrapper '#!/usr/bin/env bash
      # Wrapper around the ctags executable,
      # to set HOME back to the user'"'"'s home dir,
      # so that ctags can read config files in ~/.ctags.d/
      # (Contained snaps set HOME to $SNAP_USER_DATA instead.)
      dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
      HOME=$(python3 -SIBc '"'"'
      import os, pwd
      print(pwd.getpwuid(os.getuid()).pw_dir)
      '"'"') $dir/bin/ctags $@
      '
      chmod a+x universal-ctags-wrapper

